### ISSUE TITLE
Want to make issue template 

### ISSUE THREAD

**Issue by AnitSarkar123** [eccentriccoder01/VoyageVista#11]
Assign me under Aperture'24

**Comment by eccentriccoder01** [comment]
> Assign me under Aperture'24

Assigned you, 1 day for this, go ahead❕

**Comment by eccentriccoder01** [comment]
@AnitSarkar123 ❔

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 ❔

Sorry for late I will send a pr today i can't solve it because of our college MCQ exam...today the exam is finished

**Comment by eccentriccoder01** [comment]
@AnitSarkar123 Well Done❕
