### ISSUE TITLE
Adding the email receive functionality in the contact us section

### ISSUE THREAD

**Issue by AnitSarkar123** [eccentriccoder01/VoyageVista#15]
### Describe your issue

Email is not sent to owner of website from contact us

### Steps to reproduce

I want to implement it by Email js...to get the api key owner required to register in email js

### What was the expected result?

Email go to the owner of the code or website..from contact us section 

### Would you like to work on this issue?

Yes

**Comment by eccentriccoder01** [comment]
> ### Describe your issue
> Email is not sent to owner of website from contact us
> 
> ### Steps to reproduce
> I want to implement it by Email js...to get the api key owner required to register in email js
> 
> ### What was the expected result?
> Email go to the owner of the code or website..from contact us section
> 
> ### Put here any screenshots or videos (optional)
> _No response_
> 
> ### Would you like to work on this issue?
> Yes

Assigned you, 3 days for this, go ahead❕
