### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by arghadipmanna101** [eccentriccoder01/VoyageVista#18]
### Describe the feature

- will add project related photos
- will add gif
- will stylize the readme
- will add how to contribute

### Would you like to work on this issue?

None

**Comment by arghadipmanna101** [comment]
please assign me under Apertre

**Comment by eccentriccoder01** [comment]
> please assign me under Apertre

Assigned you, 1 day for this, go ahead👍🏻

**Comment by arghadipmanna101** [comment]
ok. thank you
