### ISSUE TITLE
Add new feature : API boxes 

### ISSUE THREAD

**Issue by apu52** [eccentriccoder01/VoyageVista#19]
### Describe the feature

Hello Sir,
I want to add some cool badges in this repo

### It should be implemented because

I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.

### Additional context

![image](https://github.com/sayandippaul/dropling-chatapp/assets/114172928/d629c5df-45db-4ad4-9097-1311e862a2d1)

### Would you like to work on this issue?

Yes

**Comment by apu52** [comment]
@eccentriccoder01 Please assign me this issue under APERTRE'24

**Comment by eccentriccoder01** [comment]
> @eccentriccoder01 Please assign me this issue under APERTRE'24

Assigned you, go ahead, today is the deadline of the event
