### ISSUE TITLE
[FEAT] Add a Page not found - 404 page 

### ISSUE THREAD

**Issue by RuthwikReddy09** [eccentriccoder01/VoyageVista#4]
Adding a page not found - 404 page will improve the user experience.
Currently it displays a blank white screen instead of 404 page.

**Comment by eccentriccoder01** [comment]
Assigned you, go ahead❕

**Comment by eccentriccoder01** [comment]
@RuthwikReddy09 jus' give me your LinkedIn profile ID if you can...

**Comment by RuthwikReddy09** [comment]
> @RuthwikReddy09 jus' give me your LinkedIn profile ID if you can...

Sure, https://www.linkedin.com/in/ruthwik-reddy-doodipala-482292228/
