### ISSUE TITLE
By clicking on the e-mail and number the user directly redirect to the email sending app and phone calling app

### ISSUE THREAD

**Issue by AnitSarkar123** [eccentriccoder01/VoyageVista#7]
Mainly I want to implement this
https://github.com/eccentriccoder01/VoyageVista/assets/135215478/b070bd43-719b-456f-9997-a409a1f146b7

**Comment by AnitSarkar123** [comment]
Assign me under Aperture'24

**Comment by eccentriccoder01** [comment]
Assigned you, 2 days for you, go ahead
All the best👍🏻

**Comment by eccentriccoder01** [comment]
@AnitSarkar123 Good Job❕
